language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

.steps:
  - &add-composer-bin-dir-to-path |
      export PATH="$PATH:$HOME/.composer/vendor/bin"
  - &clear-test-app-cache |
      tests/Fixtures/app/console cache:clear
  - &disable-php-memory-limit |
      echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - &disable-xdebug-php-extension |
      phpenv config-rm xdebug.ini || echo "xdebug not available"
  - &install-mongodb-php-extension |
      echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/mongodb.ini
  - &run-behat-tests |
      vendor/bin/behat --format=progress --no-interaction
  - &run-phpunit-tests |
      vendor/bin/phpunit
  - &update-project-dependencies |
      composer update --prefer-dist --no-progress --no-suggest --ansi
  - &validate-openapi-v2-json |
      tests/Fixtures/app/console api:swagger:export > swagger.json && npx swagger-cli validate swagger.json && rm swagger.json
  - &validate-openapi-v2-yaml |
      tests/Fixtures/app/console api:swagger:export --yaml > swagger.yaml && npx swagger-cli validate swagger.yaml && rm swagger.yaml
  - &validate-openapi-v3-json |
      tests/Fixtures/app/console api:openapi:export --spec-version 3 > swagger.json && npx swagger-cli validate swagger.json && rm swagger.json
  - &validate-openapi-v3-yaml |
      tests/Fixtures/app/console api:openapi:export --spec-version 3 --yaml > swagger.yaml && npx swagger-cli validate swagger.yaml && rm swagger.yaml

jobs:
  include:
    - php: 7.4snapshot
      before_install:
        - *install-mongodb-php-extension
        - *disable-xdebug-php-extension
        - *disable-php-memory-limit
        - *add-composer-bin-dir-to-path
      install:
        - *update-project-dependencies
      before_script:
        - *clear-test-app-cache
      script:
        - *run-phpunit-tests
        - *clear-test-app-cache
        - *run-behat-tests
        - *validate-openapi-v2-json
        - *validate-openapi-v2-yaml
        - *validate-openapi-v3-json
        - *validate-openapi-v3-yaml
  allow_failures:
    - env: SYMFONY_DEPRECATIONS_HELPER=max[total]=5 # 5 deprecation notices from FOSUserBundle
  fast_finish: true
